substitutions:
  temperature_update_time: 5s
  publish_wind_interval: 5s
  publish_temperature_interval: 60s
  device_name: "1wire"
  appversion: "1.0.0"
  base_topic: "home/1wire"

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32-poe-iso

globals:
  - id: current_screen
    type: int
    restore_value: no
    initial_value: '0'

packages:
  mqtt:     !include config/mqtt.yaml
  ethernet: !include config/ethernet.yaml
  i2c:      !include config/i2c.yaml

# Enable logging
logger:
  #level: WARN
  level: DEBUG

# Enable Home Assistant API
api:
  password: "1234"

ota:
  password: "1234"

web_server:
  port: 80

# Example configuration entry
dallas:
  - pin: GPIO5
    update_interval: ${temperature_update_time}

# Individual sensors
sensor:
  - <<: !include sensors/temperature/haus_ug_server_raum.yaml
  - <<: !include sensors/temperature/haus_ug_server_rack.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_brauchwasser.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_gas_vl.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_gas_rl.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_hk_og_vl.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_hk_og_rl.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_solar_vl.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_solar_rl.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_hk_eg_vl.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_hk_eg_rl.yaml
  - <<: !include sensors/temperature/haus_ug_lueftung_eingang.yaml
  - <<: !include sensors/temperature/haus_ug_lueftung_ausgang.yaml
  - <<: !include sensors/temperature/haus_ug_heizung_raum.yaml
  - <<: !include sensors/temperature/haus_ug_lager_raum.yaml

  - <<: !include ./mqtt/json/temperature/haus_ug_server_raum.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_server_rack.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_brauchwasser.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_gas_vl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_gas_rl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_hk_og_vl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_hk_og_rl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_solar_vl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_solar_rl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_hk_eg_vl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_hk_eg_rl.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_lueftung_eingang.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_lueftung_ausgang.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_heizung_raum.yaml
  - <<: !include ./mqtt/json/temperature/haus_ug_lager_raum.yaml

  # Internal temperature sensor
  - <<: !include sensors/internal.yaml
  - <<: !include mqtt/json/internal.yaml

  # Internal DHT sensor
  - <<: !include sensors/dht.yaml
  - <<: !include mqtt/json/dht.yaml
