
- platform: dallas
  address: 0x0118339334FF28
  name: "haus/ug/server/raum"
  id: haus_ug_server_raum
  internal: true

- platform: dallas
  address: 0x01143381775128
  name: "haus/ug/server/rack"
  id: haus_ug_server_rack
  internal: true

- platform: dallas
  address: 0x0416C229E6FF28
  name: "haus/ug/heizung/brauchwasser"
  id: haus_ug_heizung_brauchwasser
  internal: true

- platform: dallas
  address: 0x021833568DFF28
  name: "haus/ug/heizung/gas_vl"
  id: haus_ug_heizung_gas_vl
  internal: true

- platform: dallas
  address: 0x0118335639FF28
  name: "haus/ug/heizung/gas_rl"
  id: haus_ug_heizung_gas_rl
  internal: true

- platform: dallas
  address: 0x01183357F0FF28
  name: "haus/ug/heizung/hk_og_vl"
  id: haus_ug_heizung_hk_og_vl
  internal: true

- platform: dallas
  address: 0x02183318D6FF28
  name: "haus/ug/heizung/hk_og_rl"
  id: haus_ug_heizung_hk_og_rl
  internal: true

- platform: dallas
  address: 0x0516B573C8FF28
  name: "haus/ug/heizung/solar_vl"
  id: haus_ug_heizung_solar_vl
  internal: true

- platform: dallas
  address: 0x0416C222D4FF28
  name: "haus/ug/heizung/solar_rl"
  id: haus_ug_heizung_solar_rl
  internal: true

- platform: dallas
  address: 0x0516B5762DFF28
  name: "haus/ug/heizung/hk_eg_vl"
  id: haus_ug_heizung_hk_eg_vl
  internal: true

- platform: dallas
  address: 0x0416C1D2F2FF28
  name: "haus/ug/heizung/hk_eg_rl"
  id: haus_ug_heizung_hk_eg_rl
  internal: true

- platform: dallas
  address: 0x0114336F554028
  name: "haus/ug/lueftung/eingang"
  id: haus_ug_lueftung_eingang
  internal: true

- platform: dallas
  address: 0x011432B05DD428
  name: "haus/ug/lueftung/ausgang"
  id: haus_ug_lueftung_ausgang
  internal: true

- platform: dallas
  address: 0x01143390AA3528
  name: "haus/ug/heizung/raum"
  id: haus_ug_heizung_raum
  internal: true

- platform: dallas
  address: 0x01143361327628
  name: "haus/ug/lager/raum"
  id: haus_ug_lager_raum
  internal: true