
- platform: uptime
  id: publish_haus_ug_lueftung_eingang_json
  update_interval: ${publish_temperature_interval}
  on_value:
    if:
      condition:
        lambda: 'return !isnan(id(haus_ug_lueftung_eingang).state);'
      then:
        - mqtt.publish_json:
            topic: ${base_topic}/haus/ug/lueftung/eingang
            retain: True
            payload: |-
              root["temperature"] = round(id(haus_ug_lueftung_eingang).state * 100) / 100;