
- platform: uptime
  id: publish_ug_heizung_brauchwasser_json
  update_interval: ${publish_temperature_interval}
  on_value:
    if:
      condition:
        lambda: 'return !isnan(id(ug_heizung_brauchwasser).state);'
      then:
        - mqtt.publish_json:
            topic: ${base_topic}/ug/heizung/brauchwasser
            retain: True
            payload: |-
              root["temperature"] = round(id(ug_heizung_brauchwasser).state * 100) / 100;