
- platform: uptime
  id: publish_ug_heizung_gas_rl_json
  update_interval: ${publish_temperature_interval}
  on_value:
    if:
      condition:
        lambda: 'return !isnan(id(ug_heizung_gas_rl).state);'
      then:
        - mqtt.publish_json:
            topic: ${base_topic}/ug/heizung/gas_rl
            retain: True
            payload: |-
              root["temperature"] = round(id(ug_heizung_gas_rl).state * 100) / 100;
