
- platform: uptime
  id: publish_ug_lueftung_ausgang_json
  update_interval: ${publish_temperature_interval}
  on_value:
    if:
      condition:
        lambda: 'return !isnan(id(ug_lueftung_ausgang).state);'
      then:
        - mqtt.publish_json:
            topic: ${base_topic}/ug/lueftung/ausgang
            retain: True
            payload: |-
              root["temperature"] = round(id(ug_lueftung_ausgang).state * 100) / 100;