name: 'Build firmware'
on:
  workflow_dispatch:
  push:

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: esphome/build-action@v1
        with:
          yaml_file: app.yaml
